
# имя параметра - произвольная строка (рекомендуется префикс 'app.'
# для лучшей дифференциации ваших параметров от параметров Symfony).
db: 'todo'

# булевы параметры
enable_v2_protocol: true

# параметры массива/коллекции
supported_locales: ['en', 'es', 'fr']

# параметры бинарного содержания (зашифруйте его с помощью base64_encode())
some_parameter: !!binary VGhpcyBpcyBhIEJlbGwgY2hhciAH

# PHP-константы в качестве значений параметра
some_constant: !php/const GLOBAL_CONSTANT
another_constant: !php/const App\Entity\BlogPost::MAX_ITEMS